// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0QNBrOREwxQwiop8FYLKotcpDG_lOqQ',
    appId: '1:25837029385:web:c2f92ac1999f710a8d50d8',
    messagingSenderId: '25837029385',
    projectId: 'chargerrr-5c735',
    authDomain: 'chargerrr-5c735.firebaseapp.com',
    storageBucket: 'chargerrr-5c735.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6xM1l44M2rYF4tfOmY8wlqvd7Lm3ntN0',
    appId: '1:25837029385:android:ff5deb25bc99e5ee8d50d8',
    messagingSenderId: '25837029385',
    projectId: 'chargerrr-5c735',
    storageBucket: 'chargerrr-5c735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-9N1lP_pVfoi6z_Aucy4EFhx-KqFOAA',
    appId: '1:25837029385:ios:67619c08f25c57888d50d8',
    messagingSenderId: '25837029385',
    projectId: 'chargerrr-5c735',
    storageBucket: 'chargerrr-5c735.firebasestorage.app',
    iosBundleId: 'com.example.chargerrrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC-9N1lP_pVfoi6z_Aucy4EFhx-KqFOAA',
    appId: '1:25837029385:ios:67619c08f25c57888d50d8',
    messagingSenderId: '25837029385',
    projectId: 'chargerrr-5c735',
    storageBucket: 'chargerrr-5c735.firebasestorage.app',
    iosBundleId: 'com.example.chargerrrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq0QNBrOREwxQwiop8FYLKotcpDG_lOqQ',
    appId: '1:25837029385:web:dda0dc32d55e9a3b8d50d8',
    messagingSenderId: '25837029385',
    projectId: 'chargerrr-5c735',
    authDomain: 'chargerrr-5c735.firebaseapp.com',
    storageBucket: 'chargerrr-5c735.firebasestorage.app',
  );
}
